plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url "https://maven.fabricmc.net/" }
	maven { url "https://repo.spongepowered.org/repository/maven-public/" }
	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url "https://api.modrinth.com/maven" }
}

fabricApi {
	configureDataGeneration()
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "maven.modrinth:yacl:${project.yacl_version}"
	implementation "maven.modrinth:modmenu:${project.modmenu_version}"
}

def replaceProperties = [
		version: version,
		java_version: java_version,
		loader_version: loader_version,
		minecraft_version: minecraft_version,
		minecraft_version_compatible: minecraft_version_compatible,
		fabric_version: fabric_version,
		yacl_version: yacl_version,
		modmenu_version: modmenu_version,
]

processResources {
	inputs.properties replaceProperties
	replaceProperties.put 'project', project

	filesMatching("fabric.mod.json") {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version.toInteger()
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	// withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	archiveClassifier = ""
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}