org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

java_version=21

# https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2

minecraft_version_compatible=1.21.11

mod_version=1.7.0+1.21.11+fabric
maven_group=net.lugo.utools
archives_base_name=utools

# https://linkie.shedaniel.dev/dependencies?loader=fabric
fabric_version=0.139.5+1.21.11
yacl_version=3.8.1+1.21.11-fabric
modmenu_version=17.0.0-alpha.1