org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

java_version=21

# https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

minecraft_version_compatible=~26.1

mod_version=1.8.2+26.1+fabric
maven_group=net.lugo.utools
archives_base_name=utools

# https://linkie.shedaniel.dev/dependencies?loader=fabric
fabric_version=0.144.3+26.1
yacl_version=3.9.1+26.1-fabric
modmenu_version=18.0.0-alpha.8